services:
  - type: worker
    name: prayerforce-bot
    runtime: python
    rootDir: bot
    buildCommand: pip install -r requirements.txt && PRISMA_BINARY_CACHE_DIR=/opt/render/project/src/bot prisma generate --schema=database/schema.prisma && PRISMA_BINARY_CACHE_DIR=/opt/render/project/src/bot prisma py fetch
    startCommand: python main.py
    envVars:
      - key: PRISMA_BINARY_CACHE_DIR
        value: /opt/render/project/src/bot
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: "1"
